name: Trivy Container Scan

on:
 push:

jobs:
  scan:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - run: docker build -t demo:v1
   - uses: aquasecurity/trivy-action@master
   with:
     image-ref: demo:v1
     format: table
  
